### ISSUE TITLE
Recommend "First and Middle Name" as one mandatory field for applicants

### ISSUE THREAD

**Issue by daqattack** [worbli/portal-v2-uat#12]
From my experience with Onfido (if we're still using them), the Middle Name option should be made into a mandatory field, unless for Chinese, Koreans or others who do not have middle names. Because if not, Onfido will return us tons of mismatches simply because if David James Smith is a criminal and David Keith Smith submitted an application with us without giving his middle name, then he will be flagged on Watchlist report by Onfido. This was one of the major reasons why Onfido returned so many Watchlist cases to us. I talked with Todor about this, and he suggested to combine the name fields and make it "First and Middle Name" as one field for people to fill out. If they have a middle name, they should give it to us; if they really don't have one, they should ignore it.

**Comment by tkaraivanov** [comment]
Thanks Daqian. We were considering this but decided to go with separate fields after consultation with Mahdi from Onfido. The problem is that we can't split the combined names programmatically, as there are persons who have more than one name as "first name".

We are considering other design solutions for making sure people give us their middle name if they have it.
